// Whitelist of tables exposed via /api/admin. Any name not on this list
// returns 400 before a Supabase query is dispatched. `payment_invoices` is
// intentionally excluded — it carries wallet/PII fields. It is still
// reachable as a *join* from orders (PostgREST resolves nested selects)
// but direct top-level access is disallowed.
const VALID_TABLES = [
  "users",
  "products",
  "product_variants",
  "product_images",
  "product_attributes",
  "product_attribute_values",
  "product_attribute_configs",
  "product_variant_attributes",
  "product_details",
  "product_rich_descriptions",
  "product_categories",
  "categories",
  "brands",
  "inventory",
  "orders",
  "order_items",
  "payments",
  "reviews",
  "articles",
  "events",
  "faqs",
  "notifications",
  "addresses",
  "wishlists",
  "wishlist_items",
  "admins",
  "admin_login_emails",
  "roles",
  "permissions",
  "role_permissions",
  "auth_sessions",
  "delivery_zones",
  "social_links",
  "policies",
  "banners",
  "coupons",
  "coupon_products",
  "coupon_categories",
  "coupon_brands",
  "coupon_usages",
  "user_coupons",
  "bank_accounts",
  "branches",
  "branch_inventory",
  "ads",
  "about_sections",
  "team_members",
  "sms_campaigns",
  "sms_logs",
  "stock_history",
  "settings",
  "warehouses",
  "warehouse_inventory",
  "admin_notifications",
  "payment_logs",
  "point_transactions",
  "user_notes",
];

export function isValidTable(table: string): boolean {
  return VALID_TABLES.includes(table);
}
